auth/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import *

app_name = "qux_auth"

urlpatterns = [
    path("signup/", signup, name="signup"),
    path("activate/<uidb64>/<token>/", activate, name="activate"),
    path(
        "login/", CoreLoginView.as_view(redirect_authenticated_user=True), name="login"
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path(r"password-reset/", CorePasswordResetView.as_view(), name="password_reset"),
    path(
        r"password-reset/done/",
        CorePasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        r"reset/<uidb64>/<token>/",
        CorePasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        r"reset/done/",
        CorePasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path(
        r"needhelp/",
        TemplateView.as_view(template_name="login.html"),
        name="support_request",
    ),
]

templates/forms/_field.html
{% load quxform %}
{% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}

{% for field in form.visible_fields %}
  <!-- {{ field }} -->
  <div class="form-group row">
    <div class="col">
    {% if field|is_checkbox %}

    <div class="input-group">
      <div class="input-group-prepend">
        <div class="input-group-text foo-border pl-3" style="width: 44px;">
          {{ field }}
        </div>
      </div>
      <input type="text" class="form-control foo-border" value="{{ field.label|upper }}" readonly>
    </div>

    {% else %}
      {% if field.name == 'password' and changepassword %}
        <div class="bg-warning">
          <div class="d-inline-block float-right text-danger">
            <a href="/password-reset/" tabindex="-1">Forgot password?</a>
          </div>
        </div>
      {% endif %}

      {# Show Need Help? if the first attempt to login is unsuccessful #}
      {% if field.name == "username" and needhelp and form.non_field_errors %}
        <div class="bg-warning">
          <div class="d-inline-block float-right text-info text-danger">
            <a href="{% url 'qux_auth:support_request' %}">Need Help?</a>
          </div>
        </div>
      {% endif %}

      <label for="{{ field.id }}" class="form-label">
        {{ field.label }}

        {% if field.field.required %}
        <span style="color: red;">*</span>
        {% endif %}
      </label>

      {{ field }}

      {% if field.help_text %}
        <small class="input-tip-text text-muted">{{ field.help_text }}</small>
      {% endif %}

      {% for error in field.errors %}
        <small class="input-err-text text-muted">{{ error }}</small>
      {% endfor %}

    {% endif %}
    </div>
  </div>
{% endfor %}

templates/forms/_form.html
{% extends '_blank.html' %}
{% load static i18n quxform %}

{% if canonical %}
{% block og_url %}{{ canonical }}{% endblock %}
{% block canonical %}{{ canonical }}{% endblock %}
{% endif %}

{% block customstyle %}
  {{ block.super }}
  <style>
  .h1, h1 {
      font-size: 2rem;
      font-weight: 300;
  }
  body {
      background: {% block body-md-background %}{% endblock body-md-background %} !important;
  }
  #form-container {
    max-width: 480px;
    margin-left: auto;
    margin-right: auto;
  }
  /*
  @media screen and (min-width: 768px) and (max-width: 991px) {
    #form-container { max-width: 736px; }
  }
  */
  @media screen and (max-width: 767px) {
    body { background: unset !important; }
    #form-container { box-shadow: none !important; }
  }
  </style>
{% endblock customstyle %}

{% block rawcontent %}
  {{ block.super }}

  {# I do not remember what form_prefix intent is #}
  <div>
  {% block form_prefix %}{% endblock form_prefix %}
  </div>

  {% block form_container %}
  <div class="container-md my-4">
    <div id="form-container">

    {# form_title is what is displayed #}
    <h1 class="mb-4">{% block form_title %}{% endblock form_title %}</h1>

    {# typically include '_form.html' #}
    {% block form_body %}
    {% endblock form_body %}
    </div>
  </div>
  {% endblock form_container %}

  <div class="container-md my-4"><div id="form-container" class="px-md-4">
  {% block form_belowthefold %}
  {% endblock form_belowthefold %}
  </div></div>
{% endblock %}

templates/forms/_hfields.html
{% load quxform %}
{% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}

{{ form.non_field_errors }}

{% for field in form.visible_fields %}
  {% if field.field.widget.attrs.group_label %}
  <div class="form-group row">
    <div class="col-12 col-sm-12 text-center">
      <h5>{{ field.field.widget.attrs.group_label }}</h5>
    </div>
  </div>
  {% endif %}

  <div class="form-group row">
    {# checkbox #}
    {# getbootstrap.com/docs/4.6/components/forms/#horizontal-form #}
    {% if 'form-check-input' in field.field.widget.attrs.class %}
    <div class="col-12 offset-sm-4 col-sm-8 offset-md-3 col-md-9 offset-xl-2 col-xl-10">
      <div class="form-check">
        {{ field }}
        <label id="label_{{ field.auto_id }}" for="{{ field.id_for_label }}" class="form-check-label">
          {{ field.label }}
        </label>
      </div>
    </div>
    {# END checkbox #}

    {% else %}
    <label for="{{ field.id_for_label }}" class="col-12 col-sm-4 col-md-3 col-xl-2 col-form-label">
      {{ field.label }}
      {% if field.field.required %}
        <span style="color: red;">*</span>
      {% endif %}
    </label>

    <div class="col-12 col-sm-8 col-md-9 col-xl-10 align-self-center">
      {# getbootstrap.com/docs/4.6/components/forms/#custom-forms #}

      {# getbootstrap.com/docs/4.6/components/input-group/#custom-file-input #}
      {% if 'custom-file-input' in field.field.widget.attrs.class %}
      <div class="custom-file">
        {{ field }}
        <label id="label_{{ field.auto_id }}" for="{{ field.id_for_label }}" class="custom-file-label">
          Choose File
        </label>
      </div>

      {# getbootstrap.com/docs/4.6/components/forms/#switches #}
      {% elif 'custom-control-input' in field.field.widget.attrs.class %}
      <div class="custom-control custom-switch">
        {{ field }}
        <label id="label_{{ field.auto_id }}" for="{{ field.id_for_label }}" class="custom-control-label"></label>
      </div>

      {# getbootstrap.com/docs/4.6/components/forms/#range #}
      {% elif 'custom-range' in field.field.widget.attrs.class %}
      <div class="row">
        <div class="col-3 col-md-2 text-center">
          <span id="value_{{ field.auto_id }}">{{ field.field.widget.attrs.value }}</span>
        </div>
        <div class="col-9 col-md-10">{{ field }}</div>
      </div>
      {% else %}
      {{ field }}
      {% endif %}

      {% if field.help_text %}
        <small class="input-tip-text text-muted">{{ field.help_text }}</small>
      {% endif %}
      {% for error in field.errors %}
        <small class="input-err-text text-muted">{{ error }}</small>
      {% endfor %}
    </div>
    {% endif %}
  </div>
{% endfor %}

templates/forms/form.html
{% extends 'forms/_form.html' %}
{% load static %}
{% load quxform %}

{% block form_title %}{{ form_title }}{% endblock %}

<!-- form_body -->
{% block form_body %}
<form method="post">
  {% csrf_token %}

  {% include 'forms/_field.html' %}

  <!-- submit -->
  <div class="row mt-4"><div class="col">
    <button type="submit" class="btn btn-outline-primary btn-block my-3">
      {% if submit_btn_text %}
      {{ submit_btn_text }}
      {% else %}
      Submit
      {% endif %}
    </button>
  </div></div>
</form>
{% endblock form_body %}