token/urls.py
from django.urls import path

from .views import *

app_name = "qux_token"

urlpatterns = [
    path("", CustomTokenListView.as_view(), name="home"),
    path("new/", CustomTokenCreateView.as_view(), name="create"),
    path("<int:pk>/edit/", CustomTokenUpdateView.as_view(), name="edit"),
    path("<int:pk>/delete/", CustomTokenDeleteView.as_view(), name="delete"),
    path("<str:key>/", CustomTokenDetailView.as_view(), name="key"),
]

token/models.py
import os
from binascii import hexlify

from django.contrib.auth import get_user_model
from django.db import models
from rest_framework.authentication import TokenAuthentication

from qux.models import QuxModel


class CustomToken(QuxModel):
    key = models.CharField(max_length=40, unique=True)
    name = models.CharField(max_length=128)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Custom Token"
        verbose_name_plural = "Custom Tokens"

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = self.generate_key()
        return super().save(*args, **kwargs)

    @classmethod
    def generate_key(cls):
        return hexlify(os.urandom(20)).decode()


class CustomTokenAuthentication(TokenAuthentication):
    model = CustomToken

token/forms.py
from django import forms

from .models import CustomToken


class CustomTokenForm(forms.ModelForm):
    class Meta:
        model = CustomToken
        fields = [
            "name",
        ]

    def save(self, user=None):
        newform = super(CustomTokenForm, self).save(commit=False)
        if user:
            newform.user = user
        newform.save()
        return newform

    name = forms.CharField(
        label="Name",
        widget=forms.TextInput(
            attrs={
                "class": "form-control foo-border",
                "placeholder": "Enter name",
            }
        ),
    )

token/views.py
from django.conf import settings
# from core.mixin import DjangoViewTrackingMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.urls import reverse
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

from qux.seo.mixin import SEOMixin
from .forms import *
from .models import *


class CustomTokenListView(SEOMixin, LoginRequiredMixin, ListView):
    model = CustomToken
    queryset = CustomToken.objects.all()
    template_name = "token_list.html"
    fields = [
        "name",
    ]
    extra_context = {
        "breadcrumbs": ["API KEY"],
        "base_template": getattr(settings, "ROOT_TEMPLATE", "_blank.html"),
    }

    def get_queryset(self):
        # should not use self.queryset directly as list doesn't updated
        queryset = CustomToken.objects.all()
        queryset = queryset.filter(user=self.request.user)

        return queryset


class CustomTokenDetailView(SEOMixin, LoginRequiredMixin, DetailView):
    model = CustomToken
    template_name = "token_detail.html"
    extra_context = {
        "breadcrumbs": ["API KEY", "Detail"],
        "base_template": getattr(settings, "ROOT_TEMPLATE", "_blank.html"),
    }

    def get_object(self, *args, **kwargs):
        key = self.kwargs.get("key", None)

        obj = None
        if key:
            obj = self.model.objects.filter(user=self.request.user, key=key).first()

        if not obj:
            raise Http404

        return obj


class CustomTokenCreateView(SEOMixin, LoginRequiredMixin, CreateView):
    model = CustomToken
    form_class = CustomTokenForm
    template_name = (
        "bs5/token_create.html"
        if getattr(settings, "BOOTSTRAP", "bs4") == "bs5"
        else "token_create.html"
    )
    # fields = ['title', 'slug', 'body', 'citation', 'tags', 'is_draft', 'is_private', ]
    extra_context = {
        "breadcrumbs": ["API KEY", "New"],
        "base_template": getattr(settings, "ROOT_TEMPLATE", "_blank.html"),
    }

    def form_valid(self, form):
        form.save(self.request.user)
        return super(CustomTokenCreateView, self).form_valid(form)

    def get_success_url(self, *args, **kwargs):
        # return HttpResponseRedirect(reverse('token:home', kwargs={'key': self.object.key}))
        return reverse("qux_token:key", kwargs={"key": self.object.key})


class CustomTokenUpdateView(SEOMixin, LoginRequiredMixin, UpdateView):
    model = CustomToken
    form_class = CustomTokenForm
    template_name = (
        "bs5/token_update.html"
        if getattr(settings, "BOOTSTRAP", "bs4") == "bs5"
        else "token_update.html"
    )
    extra_context = {"base_template": getattr(settings, "ROOT_TEMPLATE", "_blank.html")}

    @staticmethod
    def get_success_url(*args, **kwargs):
        return reverse("qux_token:home")


class CustomTokenDeleteView(SEOMixin, LoginRequiredMixin, DeleteView):
    model = CustomToken
    extra_context = {"base_template": getattr(settings, "ROOT_TEMPLATE", "_blank.html")}

    @staticmethod
    def get_success_url(**kwargs):
        return reverse("qux_token:home")

token/templates/_token.html
{% extends base_template %}
{% load static i18n %}

{% block qux_content %}
  {% block ralph_messages %}{% endblock %}

  <div class="container-lg my-4"><div class="{{ user }}">
    {% block ralph_headings %}{% endblock %}
    {% block ralph %}{% endblock %}
  </div></div>
{% endblock %}

token/templates/bs5/token_create.html
{% extends '_token.html' %}
{% load static %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock stylesheets %}

{% block customstyle %}
{{ block.super }}
<style>
#form-container {
  max-width: 480px !important;
  margin: 0px auto;
}
</style>
{% endblock customstyle %}

{% block ralph_headings %}
<h1>Create API Token</h1>
{% endblock %}

{% block ralph %}
  {% block form_body %}
  <form method="post" id='form-container'>
    {% csrf_token %}
    <div class="row">
      {% for field in form.visible_fields %}
        <div class="col-12 form-group">
          <label for="{{ field.label }}" class="form-label">
            {{ field.label }}
            {% if field.field.required %}
              <span style="color: red;">*</span>
            {% endif %}
          </label>
          {{ field.errors }}
          <div class="input-group">
            {{ field }}
          </div>
        </div>
      {% endfor %}
    </div>

    <div class="d-grid gap-2">
      <button type="submit" class="btn btn-outline-primary py-2">
        Create
      </button>
    </div>
  </form>
  {% endblock form_body %}
{% endblock ralph %}

token/templates/bs5/token_delete.html
{% extends 'app/_app_hform.html' %}
{% load static %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock stylesheets %}

{% block form_title %}Manage Key{% endblock %}

{% block form_body %}
<form method="post">
  {% csrf_token %}
  <div class="row">
    <div class="col-12 form-group">
      <label for="key_name" class="form-label">
        Name <span style="color: red;">*</span>
      </label>
      <input type="text" class="form-control foo-border"
             id="key_name" name="key_name" value="{{ object.name }}">
    </div>
  </div>

  <div class="d-grid gap-2">
    <button type="submit" class="btn btn-outline-primary py-2">
      Rename
    </button>
  </div>
</form>
{% endblock form_body %}

token/templates/bs5/token_update.html
{% extends 'forms/form.html' %}
{% comment %} {% extends 'app/_app_hform.html' %} {% endcomment %}
{% load static %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock stylesheets %}

{% block form_title %}Manage Key{% endblock %}

{% block form_body %}
  <form method="post">
    {% csrf_token %}
    <div class="row">
      {% for field in form.visible_fields %}
        <div class="col-12 form-group">
          <label for="{{ field.label }}" class="form-label">
            {{ field.label }}
            {% if field.field.required %}
              <span style="color: red;">*</span>
            {% endif %}
          </label>
          {{ field.errors }}
          <div class="input-group">
            {{ field }}
          </div>
        </div>
      {% endfor %}
    </div>

    <div class="d-grid gap-2">
      <button type="submit" class="btn btn-outline-primary py-2">
        Rename
      </button>
    </div>
  </form>
{% endblock form_body %}

token/templates/token_create.html
{% extends '_token.html' %}
{% load static %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock stylesheets %}

{% block customstyle %}
{{ block.super }}
<style>
#form-container {
  max-width: 480px !important;
  margin: 0px auto;
}
</style>
{% endblock customstyle %}

{% block ralph_headings %}
<h1>Create API Token</h1>
{% endblock %}

{% block ralph %}
  {% block form_body %}
  <form method="post" id='form-container'>
    {% csrf_token %}
    <div class="row">
      {% for field in form.visible_fields %}
        <div class="col-12 form-group">
          <label for="{{ field.label }}" class="form-label">
            {{ field.label }}
            {% if field.field.required %}
              <span style="color: red;">*</span>
            {% endif %}
          </label>
          {{ field.errors }}
          <div class="input-group">
            {{ field }}
          </div>
        </div>
      {% endfor %}
    </div>

    <div class="row mt-4">
      <div class="col">
        <button type="submit" class="btn btn-primary btn-block py-2">
          Create
        </button>
      </div>
    </div>
  </form>
  {% endblock form_body %}
{% endblock ralph %}

token/templates/token_delete.html
{% extends 'app/_app_hform.html' %}
{% load static %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock stylesheets %}

{% block form_title %}Manage Key{% endblock %}

{% block form_body %}
<form method="post">
  {% csrf_token %}
  <div class="row">
    <div class="col-12 form-group">
      <label for="key_name" class="form-label">
        Name <span style="color: red;">*</span>
      </label>
      <input type="text" class="form-control foo-border"
             id="key_name" name="key_name" value="{{ object.name }}">
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-12 col-md">
      <button class="btn btn-primary btn-block py-2">Rename</button>
    </div>
  </div>
</form>
{% endblock form_body %}

token/templates/token_detail.html
{% extends '_token.html' %}
{% load static %}

{% block ralph_headings %}
<h1>Token Details</h1>
{% endblock %}

{% block ralph %}
<div class="my-4">
  <div class="row">
    <div class="col-12">
      <p class="p-2 text-danger border border-danger rounded-lg">This key is only shown ONCE. Make note of it and
        store it in a safe, secure location.</p>
    </div>

    <div class="col-12 my-3">
      <div>
        <label>Name</label>
      </div>
      <div class="p-2 border border-secondary rounded-lg">
        {{ object.name }}
      </div>
    </div>

    <div class="col-12 my-3">
      <div>
        <label>Key</label>
      </div>
      <div class="p-2 border border-danger rounded bg-danger text-white"
        style="font-family: 'Roboto Mono', monospace; font-size: 14px; overflow: scroll">
        <span id='token-str'>{{ object.key }}</span>
        <div id="token-copy" style="display: inline;">
          <i id='token-copy-icon' class='fa fa-copy' style='cursor: pointer;'></i>
        </div>
        <div id="token-check" style="display: none;">
          <i id='token-check-icon' class='fa fa-check' style='cursor: pointer;'></i>
        </div>
        <span id='token-copied-confirmation' style='display: none'>
          Copied to clipboard
        </span>
      </div>
    </div>
  </div>

  <div class='mt-5 d-flex justify-content-center align-items-center'>
    <button class='btn btn-primary' onclick="location.href='{% url 'qux_token:home' %}'">
      Done
    </button>
  </div>
</div>
{% endblock ralph %}

{% block customjs %}
{{ block.super }}
<script>
  document.addEventListener('DOMContentLoaded', function () {
    var tokenCopyIcon = document.getElementById('token-copy');
    var tokenCheckIcon = document.getElementById('token-check');

    var tokenIcon = document.getElementById('token-copy-icon');
    var tokenCopiedConfirmation = document.getElementById('token-copied-confirmation');

    tokenCopyIcon.addEventListener('click', function () {
      navigator.clipboard.writeText(document.getElementById('token-str').innerHTML);

      tokenCopyIcon.style.display = 'none';
      tokenCheckIcon.style.display = 'inline';
      tokenCopiedConfirmation.style.display = 'block';

      // Revert back to original state
      setTimeout(function () {
        tokenCopyIcon.style.display = 'inline';
        tokenCheckIcon.style.display = 'none';
        tokenCopiedConfirmation.style.display = 'none';
      }, 3000);
    });
  });
</script>


{% endblock %}

token/templates/token_list.html
{% extends '_token.html' %}
{% load static %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/listview.css' %}">
{% endblock stylesheets %}

{% block ralph_headings %}
<h1>API Tokens</h1>

<p class='text-secondary'>
  <i class='fa fa-info-circle fa-sm'></i> API Tokens are required to identify you when you access our APIs. 
  Do not share this key anywhere public and note it down somewhere safe after you generate it as for security reason
  you will only be able to see the key once after you generate it. 
</p>
{% endblock %}

{% block ralph %}
<div class="">
  {% if object_list %}
  {% csrf_token %}
    {% for post in object_list %}
    <div class="mt-4 row no-gutters p-3 row_{{post.id}} shadow bg-light rounded-lg">
      <div class="col-8 col-md-10 pr-3">
        <div>
          <a href="{% url 'qux_token:edit' post.id %}" class="text-left text-nowrap text-truncate pr-3">
            {{ post.name }}
          </a>
        </div>

        <div class="small text-muted text-truncate">
          Created at {{post.created_at}}
        </div>
      </div>

      <div class="col-4 col-md-2 text-right align-self-center">
          <button class="btn btn-sm btn-danger text-right"
                  onclick="deletecall('{% url 'qux_token:delete' post.id %}', {{post.id}})">
            Delete
          </button>
      </div>
    </div>
    {% endfor %}
  {% else %}
  <p class="lead">You have no API Keys yet.</p>
  {% endif %}

  <div class="row my-4">
    <div class="col-12 col-md-6 text-sm-left text-nowrap">
      <a href="{% url 'qux_token:create' %}" class="btn btn-sm btn-primary text-white py-2">
        <span><i class='fa fa-plus'></i> Create New API KEY</span>
      </a>
    </div>
  </div>
</div>
{% endblock ralph %}

{% block customjs %}
{{ block.super }}
<script type="text/javascript">
  function deletecall(url, id) {
    let result = confirm("Are you sure that you want to delete this token?");
    if (result) {
      let csrftoken = document.querySelector('input[name="csrfmiddlewaretoken"]').value;
      let xhr = new XMLHttpRequest();
      xhr.open("POST", url, true);
      xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
      xhr.setRequestHeader("X-CSRFToken", csrftoken);
  
      xhr.onload = function () {
        if (xhr.status >= 200 && xhr.status < 300) {
          location.reload();
        } else {  
        }
      };

      xhr.onerror = function () {
      };

      xhr.send();
    }
  }
</script>
{% endblock %}

token/templates/token_update.html
{% extends 'forms/form.html' %}
{% comment %} {% extends 'app/_app_hform.html' %} {% endcomment %}
{% load static %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock stylesheets %}

{% block form_title %}Manage Key{% endblock %}

{% block form_body %}
<form method="post">
  {% csrf_token %}
  <div class="row">
    {% for field in form.visible_fields %}
      <div class="col-12 form-group">
        <label for="{{ field.label }}" class="form-label">
          {{ field.label }}
          {% if field.field.required %}
            <span style="color: red;">*</span>
          {% endif %}
        </label>
        {{ field.errors }}
        <div class="input-group">
          {{ field }}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="row mt-4">
    <div class="col">
      <button type="submit" class="btn btn-primary btn-block py-2">
        Rename
      </button>
    </div>
  </div>
</form>
{% endblock form_body %}